spring:
  application:
    name: books-interoperability
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BooksDb;encrypt=true;trustServerCertificate=true
    username: books_user
    password: StrongP@ssw0rd!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false

server:
  port: 8181

grpc:
  server:
    port: 9090

app:
  dhmz:
    url: https://vrijeme.hr/hrvatska_n.xml
    cache-ttl: PT10M

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    hr.algebra.books: DEBUG
    org.hibernate.SQL: DEBUG
